### ISSUE TITLE
Cannot be bundled into ESM

### ISSUE THREAD

**Issue by aral** [rooseveltframework/express-html-validator#173]
When bundled into an app that uses ECMAScript Modules, fails with:

```
/var/home/aral/.local/share/small-tech.org/kitten/app/node_modules/express-html-validator/index.js:10
const validatorErrorPage = fs.readFileSync(path.join(__dirname, 'templates/errorPage.html'))
                                                     ^
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/var/home/aral/.local/share/small-tech.org/kitten/app/dist/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at node_modules/express-html-validator/index.js (/var/home/aral/.local/share/small-tech.org/kitten/app/node_modules/express-html-validator/index.js:10:54)
    at __require2 (file:///var/home/aral/.local/share/small-tech.org/kitten/app/dist/kitten-bundle.js:17:51)
    at <anonymous> (/var/home/aral/.local/share/small-tech.org/kitten/app/src/Server.js:26:30)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.13.0
```

**Comment by kethinov** [comment]
Looks like the most important underlying dependency [html-validate](https://www.npmjs.com/package/html-validate) supports ES modules, so in principle it should be possible to make an ESM-friendly version of this module.

**Comment by kethinov** [comment]
We just added an example to the README that shows how this can be used with ESM:

```javascript
import express from 'express';
import expressValidator from 'express-html-validator'
import { fileURLToPath } from 'url'
import { dirname } from 'path'
const router = express.Router();
const app = express()
const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Generally this would be used in development mode
if (process.env.NODE_ENV === 'development') {
  expressValidator(app, config)
}

// expressValidator should be called before defining routes
router.get('/', (req, res) => {
  // This html response will be validated in real time as it's sent
  res.sendFile(__dirname + '/index.html');
})
```

@aral Does this resolve your use case, or is there still something to address here?

**Comment by aral** [comment]
Not currently using the library but from a skim of the code this should do the trick, yes. Please feel free to close this issue. Thanks :)
